spring:
  application:
    name: sb-read-properties
  cloud:
    config:
      enabled: false
  security:
    user:
      name: test12
      password: password123
    oauth2:
      client:
        registration:
          google:
            client-id: 5555555
            client-secret: xxxxxxxxxxxxxxxxxxxxx

logging:
  level:
    org.springframework.security: TRACE
server:
  port : 8085

message: "Test message"

