spring:
  application:
    name: sb-read-properties
  cloud:
    config:
      enabled: false
server:
  port : 8085

message: "Test message"

user-lists:
  users:
    user1: 100001
    user2: 100002
    user3: 100003
    user4: 100004

