spring:
  application:
    name: sb-read-properties
  cloud:
    config:
      enabled: false
server:
  port : 8085

message: "Test message"

management:
  metrics:
    enable:
      all: false
      http.server.requests: true
      system.cpu.count: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info, health, metrics, prometheus

