spring:
  application:
    name: sb-read-properties
  cloud:
    config:
      enabled: false
  security:
    user:
      name: test12
      password: password123
server:
  port : 8085

message: "Test message"

