spring:
  application:
    name: sb-read-properties
  cloud:
    config:
      enabled: false
server:
  port : 8085

message: "Test message"

management:
  endpoints:
    web:
      exposure:
        include: health, loggers

---
spring.config.activate.on-profile: local

message: "Test message in local"
